// apps/angular-demo/src/app/components/effect-settings.component.ts
import { Component, computed, output, signal } from "@angular/core";
import {
  defaultThemeEffects,
  isValidCssDuration,
} from "@brustack/theme-transitions-core";
import type {
  FlipEffectOptions,
  ThemeEffect,
  WipeEffectOptions,
} from "@brustack/theme-transitions-core";
import { IconRotateCcwComponent } from "./icons/icon-rotate-ccw.component";
import { IconSettingsComponent } from "./icons/icon-settings.component";

export interface EffectOptions {
  variant: ThemeEffect;
  duration: string;
  easing?: string;
  direction?: WipeEffectOptions["direction"] | FlipEffectOptions["direction"];
}

const defaultsFor = (variant: ThemeEffect) =>
  variant === "fade"
    ? defaultThemeEffects.fade
    : variant === "wipe"
    ? defaultThemeEffects.wipe
    : variant === "flip"
    ? defaultThemeEffects.flip
    : defaultThemeEffects.spread;

const directionDefaultFor = (variant: ThemeEffect) =>
  variant === "flip"
    ? defaultThemeEffects.flip.direction
    : defaultThemeEffects.wipe.direction;

@Component({
  selector: "app-effect-settings",
  standalone: true,
  imports: [IconRotateCcwComponent, IconSettingsComponent],
  templateUrl: "./effect-settings.component.html",
  styleUrl: "./effect-settings.component.css",
})
export class EffectSettingsComponent {
  readonly effectChange = output<{ options: EffectOptions; valid: boolean }>();

  protected readonly isOpen = signal(false);
  protected readonly variant = signal<ThemeEffect>("fade");
  protected readonly duration = signal(defaultThemeEffects.fade.duration);
  protected readonly easingPreset = signal(defaultThemeEffects.fade.easing);
  protected readonly direction = signal<
    WipeEffectOptions["direction"] | FlipEffectOptions["direction"]
  >(defaultThemeEffects.wipe.direction);
  protected readonly easingPresets = [
    "ease",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "linear",
  ];
  protected readonly wipeDirections: WipeEffectOptions["direction"][] = [
    "left",
    "right",
    "up",
    "down",
    "center-x",
    "center-y",
    "diagonal-tl",
    "diagonal-tr",
    "diagonal-bl",
    "diagonal-br",
  ];
  protected readonly flipDirections: FlipEffectOptions["direction"][] = [
    "horizontal",
    "vertical",
  ];

  protected readonly durationError = computed(() => {
    if (this.variant() === "none") return "";
    return isValidCssDuration(this.duration())
      ? ""
      : "Use a CSS duration, e.g. 1s or 400ms";
  });

  protected readonly isModified = computed(() => {
    if (this.variant() === "none") return false;

    const defaults = defaultsFor(this.variant());

    if (this.duration() !== defaults.duration) return true;
    if (this.variant() === "wipe" || this.variant() === "flip") {
      return (
        this.easingPreset() !== defaults.easing ||
        this.direction() !== directionDefaultFor(this.variant())
      );
    }

    return this.variant() === "fade" && this.easingPreset() !== defaults.easing;
  });

  constructor() {
    this.emitChange();
  }

  protected toggleOpen(): void {
    this.isOpen.update((open) => !open);
  }

  protected resetToDefaults(): void {
    const defaults = defaultsFor(this.variant());

    this.duration.set(defaults.duration);
    this.easingPreset.set(defaults.easing);
    this.direction.set(directionDefaultFor(this.variant()));
    this.emitChange();
  }

  protected selectVariant(next: ThemeEffect): void {
    const defaults = defaultsFor(next);

    this.variant.set(next);
    this.duration.set(defaults.duration);
    this.easingPreset.set(defaults.easing);
    this.direction.set(directionDefaultFor(next));
    this.emitChange();
  }

  protected onVariantChange(event: Event): void {
    this.selectVariant(
      (event.target as HTMLSelectElement).value as ThemeEffect,
    );
  }

  protected onDurationChange(event: Event): void {
    this.duration.set((event.target as HTMLInputElement).value);
    this.emitChange();
  }

  protected onEasingChange(event: Event): void {
    this.easingPreset.set((event.target as HTMLSelectElement).value);
    this.emitChange();
  }

  protected onDirectionChange(event: Event): void {
    this.direction.set(
      (event.target as HTMLSelectElement).value as
        | WipeEffectOptions["direction"]
        | FlipEffectOptions["direction"],
    );
    this.emitChange();
  }

  private emitChange(): void {
    const variant = this.variant();
    const duration = this.duration();
    const easing = this.easingPreset();
    const direction = this.direction();

    this.effectChange.emit({
      options:
        variant === "fade"
          ? { variant, duration, easing }
          : variant === "wipe" || variant === "flip"
          ? { variant, duration, easing, direction }
          : { variant, duration },
      valid: !this.durationError(),
    });
  }
}

<button
  type="button"
  class="icon-btn settings-trigger"
  [attr.aria-expanded]="isOpen()"
  aria-controls="settings-panel"
  aria-label="Effect settings"
  (click)="toggleOpen()"
>
  <app-icon-settings [size]="16" />
  @if (isModified()) {
  <span class="modified-dot" aria-hidden="true"></span>
  }
</button>

<div id="settings-panel" class="settings-collapse" [class.open]="isOpen()">
  <div class="settings-collapse-inner">
    <div class="panel-header">
      <span class="panel-title">Settings</span>
      @if (isModified()) {
      <button
        type="button"
        class="icon-btn reset"
        aria-label="Reset to defaults"
        title="Reset to defaults"
        (click)="resetToDefaults()"
      >
        <app-icon-rotate-ccw [size]="14" />
      </button>
      }
    </div>

    <div class="controls">
      <label>
        <span class="label-text">Variant</span>
        <select [value]="variant()" (change)="onVariantChange($event)">
          <option value="spread">spread</option>
          <option value="fade">fade</option>
          <option value="wipe">wipe</option>
          <option value="flip">flip</option>
          <option value="none">none</option>
        </select>
      </label>

      @if (variant() !== 'none') { @if (variant() === 'wipe' || variant() ===
      'flip') {
      <label>
        <span class="label-text">Direction</span>
        <select [value]="direction()" (change)="onDirectionChange($event)">
          @for (d of (variant() === 'wipe' ? wipeDirections : flipDirections);
          track d) {
          <option [value]="d">{{ d }}</option>
          }
        </select>
      </label>
      }

      <label>
        <span class="label-text">Duration</span>
        <input
          [value]="duration()"
          (input)="onDurationChange($event)"
          type="text"
          placeholder="1s"
          [class.invalid]="durationError()"
        />
        @if (durationError()) {
        <span class="error">{{ durationError() }}</span>
        }
      </label>

      @if (variant() === 'fade' || variant() === 'wipe' || variant() === 'flip')
      {
      <label>
        <span class="label-text">Easing</span>
        <select [value]="easingPreset()" (change)="onEasingChange($event)">
          @for (preset of easingPresets; track preset) {
          <option [value]="preset">{{ preset }}</option>
          }
        </select>
      </label>
      } }
    </div>
  </div>
</div>

// apps/react-demo/src/components/EffectSettings.tsx
import { useEffect, useState } from "react";
import {
  defaultThemeEffects,
  isValidCssDuration,
} from "@brustack/theme-transitions-core";
import type {
  FlipEffectOptions,
  ThemeEffect,
  WipeEffectOptions,
} from "@brustack/theme-transitions-core";
import { IconRotateCcw } from "./icons/IconRotateCcw";
import { IconSettings } from "./icons/IconSettings";
import "./EffectSettings.css";

export interface EffectOptions {
  variant: ThemeEffect;
  duration: string;
  easing?: string;
  direction?: WipeEffectOptions["direction"] | FlipEffectOptions["direction"];
}

export interface EffectSettingsProps {
  onChange: (options: EffectOptions, valid: boolean) => void;
}

const easingPresets = ["ease", "ease-in", "ease-out", "ease-in-out", "linear"];
const wipeDirections: WipeEffectOptions["direction"][] = [
  "left",
  "right",
  "up",
  "down",
  "center-x",
  "center-y",
  "diagonal-tl",
  "diagonal-tr",
  "diagonal-bl",
  "diagonal-br",
];
const flipDirections: FlipEffectOptions["direction"][] = [
  "horizontal",
  "vertical",
];

const defaultsFor = (variant: ThemeEffect) =>
  variant === "fade"
    ? defaultThemeEffects.fade
    : variant === "wipe"
    ? defaultThemeEffects.wipe
    : variant === "flip"
    ? defaultThemeEffects.flip
    : defaultThemeEffects.spread;

const directionDefaultFor = (variant: ThemeEffect) =>
  variant === "flip"
    ? defaultThemeEffects.flip.direction
    : defaultThemeEffects.wipe.direction;

export const EffectSettings = ({ onChange }: EffectSettingsProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const [variant, setVariant] = useState<ThemeEffect>("fade");
  const [duration, setDuration] = useState(defaultThemeEffects.fade.duration);
  const [easingPreset, setEasingPreset] = useState(
    defaultThemeEffects.fade.easing,
  );
  const [direction, setDirection] = useState<
    WipeEffectOptions["direction"] | FlipEffectOptions["direction"]
  >(defaultThemeEffects.wipe.direction);

  const durationError =
    variant === "none"
      ? ""
      : isValidCssDuration(duration)
      ? ""
      : "Use a CSS duration, e.g. 1s or 400ms";

  const isModified = (() => {
    if (variant === "none") return false;

    const defaults = defaultsFor(variant);

    if (duration !== defaults.duration) return true;
    if (variant === "wipe" || variant === "flip") {
      return (
        easingPreset !== defaults.easing ||
        direction !== directionDefaultFor(variant)
      );
    }

    return variant === "fade" && easingPreset !== defaults.easing;
  })();

  const resetToDefaults = () => {
    const defaults = defaultsFor(variant);

    setDuration(defaults.duration);
    setEasingPreset(defaults.easing);
    setDirection(directionDefaultFor(variant));
  };

  const selectVariant = (next: ThemeEffect) => {
    const defaults = defaultsFor(next);

    setVariant(next);
    setDuration(defaults.duration);
    setEasingPreset(defaults.easing);
    setDirection(directionDefaultFor(next));
  };

  useEffect(() => {
    const options: EffectOptions =
      variant === "fade"
        ? { variant, duration, easing: easingPreset }
        : variant === "wipe" || variant === "flip"
        ? { variant, duration, easing: easingPreset, direction }
        : { variant, duration };

    onChange(options, !durationError);
  }, [variant, duration, easingPreset, direction, durationError]);

  return (
    <div className="effect-settings">
      <button
        type="button"
        className="icon-btn settings-trigger"
        aria-expanded={isOpen}
        aria-controls="settings-panel"
        aria-label="Effect settings"
        onClick={() => setIsOpen(!isOpen)}
      >
        <IconSettings size={16} aria-hidden="true" />
        {isModified && <span className="modified-dot" aria-hidden="true" />}
      </button>

      <div
        id="settings-panel"
        className={`settings-collapse${isOpen ? " open" : ""}`}
      >
        <div className="settings-collapse-inner">
          <div className="panel-header">
            <span className="panel-title">Settings</span>
            {isModified && (
              <button
                type="button"
                className="icon-btn reset"
                aria-label="Reset to defaults"
                title="Reset to defaults"
                onClick={resetToDefaults}
              >
                <IconRotateCcw size={14} aria-hidden="true" />
              </button>
            )}
          </div>

          <div className="controls">
            <label>
              <span className="label-text">Variant</span>
              <select
                value={variant}
                onChange={(event) =>
                  selectVariant(event.target.value as ThemeEffect)
                }
              >
                <option value="spread">spread</option>
                <option value="fade">fade</option>
                <option value="wipe">wipe</option>
                <option value="flip">flip</option>
                <option value="none">none</option>
              </select>
            </label>

            {variant !== "none" && (
              <>
                {(variant === "wipe" || variant === "flip") && (
                  <label>
                    <span className="label-text">Direction</span>
                    <select
                      value={direction}
                      onChange={(event) =>
                        setDirection(
                          event.target.value as
                            | WipeEffectOptions["direction"]
                            | FlipEffectOptions["direction"],
                        )
                      }
                    >
                      {(variant === "wipe" ? wipeDirections : flipDirections).map(
                        (d) => (
                          <option key={d} value={d}>
                            {d}
                          </option>
                        ),
                      )}
                    </select>
                  </label>
                )}

                <label>
                  <span className="label-text">Duration</span>
                  <input
                    value={duration}
                    onChange={(event) => setDuration(event.target.value)}
                    type="text"
                    placeholder="1s"
                    className={durationError ? "invalid" : ""}
                  />
                  {durationError && (
                    <span className="error">{durationError}</span>
                  )}
                </label>

                {(variant === "fade" ||
                  variant === "wipe" ||
                  variant === "flip") && (
                  <label>
                    <span className="label-text">Easing</span>
                    <select
                      value={easingPreset}
                      onChange={(event) => setEasingPreset(event.target.value)}
                    >
                      {easingPresets.map((preset) => (
                        <option key={preset} value={preset}>
                          {preset}
                        </option>
                      ))}
                    </select>
                  </label>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
